-- =====================================================================
-- load_csvs.sql
--
-- Loads every CSV produced by generate_synthetic_data.py into a
-- database that has already had migrations 001-007 applied. Run from
-- this directory so the relative paths resolve, e.g.:
--
--   psql "<your Supabase connection string>" -f load_csvs.sql
--
-- Uses \copy (a psql client-side command, not server-side COPY) so it
-- works against a remote Supabase database without needing file access
-- on the server itself.
--
-- NULL '' tells Postgres to treat an empty CSV field as NULL rather
-- than an empty string -- required, since the generator writes "" for
-- every optional foreign key/date it left blank (e.g. a POS
-- transaction with no known customer, a driver with no employee_id).
--
-- After each load, the table's identity sequence is reset to match the
-- highest id just inserted. This is required because these tables use
-- GENERATED BY DEFAULT AS IDENTITY (see 001_core_hub.sql's header note)
-- specifically so this script could load explicit, FK-consistent ids --
-- but Postgres's own sequence counter doesn't know that happened unless
-- you tell it, so any INSERT your app does after this load would
-- otherwise collide with an id you just loaded.
-- =====================================================================

\set ON_ERROR_STOP on

-- ---- Core Services Hub ----
\copy customers FROM 'output_csv/customers.csv' WITH (FORMAT csv, HEADER true, NULL '')
SELECT setval(pg_get_serial_sequence('customers','customer_id'), COALESCE((SELECT MAX(customer_id) FROM customers), 1), true);

\copy employees FROM 'output_csv/employees.csv' WITH (FORMAT csv, HEADER true, NULL '')
SELECT setval(pg_get_serial_sequence('employees','employee_id'), COALESCE((SELECT MAX(employee_id) FROM employees), 1), true);

\copy suppliers_vendors FROM 'output_csv/suppliers_vendors.csv' WITH (FORMAT csv, HEADER true, NULL '')
SELECT setval(pg_get_serial_sequence('suppliers_vendors','supplier_id'), COALESCE((SELECT MAX(supplier_id) FROM suppliers_vendors), 1), true);

\copy locations_sites FROM 'output_csv/locations_sites.csv' WITH (FORMAT csv, HEADER true, NULL '')
SELECT setval(pg_get_serial_sequence('locations_sites','location_id'), COALESCE((SELECT MAX(location_id) FROM locations_sites), 1), true);

\copy product_service_catalogue FROM 'output_csv/product_service_catalogue.csv' WITH (FORMAT csv, HEADER true, NULL '')
SELECT setval(pg_get_serial_sequence('product_service_catalogue','product_id'), COALESCE((SELECT MAX(product_id) FROM product_service_catalogue), 1), true);

\copy financial_account_references FROM 'output_csv/financial_account_references.csv' WITH (FORMAT csv, HEADER true, NULL '')
SELECT setval(pg_get_serial_sequence('financial_account_references','account_ref_id'), COALESCE((SELECT MAX(account_ref_id) FROM financial_account_references), 1), true);

-- ---- Veridian Properties ----
\copy properties FROM 'output_csv/properties.csv' WITH (FORMAT csv, HEADER true, NULL '')
SELECT setval(pg_get_serial_sequence('properties','property_id'), COALESCE((SELECT MAX(property_id) FROM properties), 1), true);

\copy tenants FROM 'output_csv/tenants.csv' WITH (FORMAT csv, HEADER true, NULL '')
SELECT setval(pg_get_serial_sequence('tenants','tenant_id'), COALESCE((SELECT MAX(tenant_id) FROM tenants), 1), true);

\copy leases FROM 'output_csv/leases.csv' WITH (FORMAT csv, HEADER true, NULL '')
SELECT setval(pg_get_serial_sequence('leases','lease_id'), COALESCE((SELECT MAX(lease_id) FROM leases), 1), true);

\copy maintenance_requests FROM 'output_csv/maintenance_requests.csv' WITH (FORMAT csv, HEADER true, NULL '')
SELECT setval(pg_get_serial_sequence('maintenance_requests','request_id'), COALESCE((SELECT MAX(request_id) FROM maintenance_requests), 1), true);

\copy property_valuations FROM 'output_csv/property_valuations.csv' WITH (FORMAT csv, HEADER true, NULL '')
SELECT setval(pg_get_serial_sequence('property_valuations','valuation_id'), COALESCE((SELECT MAX(valuation_id) FROM property_valuations), 1), true);

\copy utility_accounts FROM 'output_csv/utility_accounts.csv' WITH (FORMAT csv, HEADER true, NULL '')
SELECT setval(pg_get_serial_sequence('utility_accounts','utility_id'), COALESCE((SELECT MAX(utility_id) FROM utility_accounts), 1), true);

\copy facility_assets FROM 'output_csv/facility_assets.csv' WITH (FORMAT csv, HEADER true, NULL '')
SELECT setval(pg_get_serial_sequence('facility_assets','asset_id'), COALESCE((SELECT MAX(asset_id) FROM facility_assets), 1), true);

-- ---- Concord Logistics ----
\copy vehicles FROM 'output_csv/vehicles.csv' WITH (FORMAT csv, HEADER true, NULL '')
SELECT setval(pg_get_serial_sequence('vehicles','vehicle_id'), COALESCE((SELECT MAX(vehicle_id) FROM vehicles), 1), true);

\copy drivers FROM 'output_csv/drivers.csv' WITH (FORMAT csv, HEADER true, NULL '')
SELECT setval(pg_get_serial_sequence('drivers','driver_id'), COALESCE((SELECT MAX(driver_id) FROM drivers), 1), true);

\copy shipments FROM 'output_csv/shipments.csv' WITH (FORMAT csv, HEADER true, NULL '')
SELECT setval(pg_get_serial_sequence('shipments','shipment_id'), COALESCE((SELECT MAX(shipment_id) FROM shipments), 1), true);

\copy shipment_legs FROM 'output_csv/shipment_legs.csv' WITH (FORMAT csv, HEADER true, NULL '')
SELECT setval(pg_get_serial_sequence('shipment_legs','leg_id'), COALESCE((SELECT MAX(leg_id) FROM shipment_legs), 1), true);

\copy routes FROM 'output_csv/routes.csv' WITH (FORMAT csv, HEADER true, NULL '')
SELECT setval(pg_get_serial_sequence('routes','route_id'), COALESCE((SELECT MAX(route_id) FROM routes), 1), true);

\copy warehouses FROM 'output_csv/warehouses.csv' WITH (FORMAT csv, HEADER true, NULL '')
SELECT setval(pg_get_serial_sequence('warehouses','warehouse_id'), COALESCE((SELECT MAX(warehouse_id) FROM warehouses), 1), true);

\copy maintenance_logs FROM 'output_csv/maintenance_logs.csv' WITH (FORMAT csv, HEADER true, NULL '')
SELECT setval(pg_get_serial_sequence('maintenance_logs','maintenance_id'), COALESCE((SELECT MAX(maintenance_id) FROM maintenance_logs), 1), true);

-- ---- Veridian Financial Services ----
\copy wallet_accounts FROM 'output_csv/wallet_accounts.csv' WITH (FORMAT csv, HEADER true, NULL '')
SELECT setval(pg_get_serial_sequence('wallet_accounts','wallet_id'), COALESCE((SELECT MAX(wallet_id) FROM wallet_accounts), 1), true);

\copy wallet_transactions FROM 'output_csv/wallet_transactions.csv' WITH (FORMAT csv, HEADER true, NULL '')
SELECT setval(pg_get_serial_sequence('wallet_transactions','wallet_txn_id'), COALESCE((SELECT MAX(wallet_txn_id) FROM wallet_transactions), 1), true);

\copy loans FROM 'output_csv/loans.csv' WITH (FORMAT csv, HEADER true, NULL '')
SELECT setval(pg_get_serial_sequence('loans','loan_id'), COALESCE((SELECT MAX(loan_id) FROM loans), 1), true);

\copy loan_repayments FROM 'output_csv/loan_repayments.csv' WITH (FORMAT csv, HEADER true, NULL '')
SELECT setval(pg_get_serial_sequence('loan_repayments','repayment_id'), COALESCE((SELECT MAX(repayment_id) FROM loan_repayments), 1), true);

\copy kyc_records FROM 'output_csv/kyc_records.csv' WITH (FORMAT csv, HEADER true, NULL '')
SELECT setval(pg_get_serial_sequence('kyc_records','kyc_id'), COALESCE((SELECT MAX(kyc_id) FROM kyc_records), 1), true);

\copy merchant_settlements FROM 'output_csv/merchant_settlements.csv' WITH (FORMAT csv, HEADER true, NULL '')
SELECT setval(pg_get_serial_sequence('merchant_settlements','settlement_id'), COALESCE((SELECT MAX(settlement_id) FROM merchant_settlements), 1), true);

-- ---- Meridian Retail ----
\copy stores FROM 'output_csv/stores.csv' WITH (FORMAT csv, HEADER true, NULL '')
SELECT setval(pg_get_serial_sequence('stores','store_id'), COALESCE((SELECT MAX(store_id) FROM stores), 1), true);

\copy pos_transactions FROM 'output_csv/pos_transactions.csv' WITH (FORMAT csv, HEADER true, NULL '')
SELECT setval(pg_get_serial_sequence('pos_transactions','transaction_id'), COALESCE((SELECT MAX(transaction_id) FROM pos_transactions), 1), true);

\copy transaction_line_items FROM 'output_csv/transaction_line_items.csv' WITH (FORMAT csv, HEADER true, NULL '')
SELECT setval(pg_get_serial_sequence('transaction_line_items','line_item_id'), COALESCE((SELECT MAX(line_item_id) FROM transaction_line_items), 1), true);

\copy inventory_stock_levels FROM 'output_csv/inventory_stock_levels.csv' WITH (FORMAT csv, HEADER true, NULL '')
SELECT setval(pg_get_serial_sequence('inventory_stock_levels','stock_id'), COALESCE((SELECT MAX(stock_id) FROM inventory_stock_levels), 1), true);

\copy promotions FROM 'output_csv/promotions.csv' WITH (FORMAT csv, HEADER true, NULL '')
SELECT setval(pg_get_serial_sequence('promotions','promotion_id'), COALESCE((SELECT MAX(promotion_id) FROM promotions), 1), true);

\copy loyalty_accounts FROM 'output_csv/loyalty_accounts.csv' WITH (FORMAT csv, HEADER true, NULL '')
SELECT setval(pg_get_serial_sequence('loyalty_accounts','loyalty_id'), COALESCE((SELECT MAX(loyalty_id) FROM loyalty_accounts), 1), true);

\copy supplier_deliveries FROM 'output_csv/supplier_deliveries.csv' WITH (FORMAT csv, HEADER true, NULL '')
SELECT setval(pg_get_serial_sequence('supplier_deliveries','delivery_id'), COALESCE((SELECT MAX(delivery_id) FROM supplier_deliveries), 1), true);

-- ---- AgriCore ----
\copy farms FROM 'output_csv/farms.csv' WITH (FORMAT csv, HEADER true, NULL '')
SELECT setval(pg_get_serial_sequence('farms','farm_id'), COALESCE((SELECT MAX(farm_id) FROM farms), 1), true);

\copy farmers FROM 'output_csv/farmers.csv' WITH (FORMAT csv, HEADER true, NULL '')
SELECT setval(pg_get_serial_sequence('farmers','farmer_id'), COALESCE((SELECT MAX(farmer_id) FROM farmers), 1), true);

\copy harvest_batches FROM 'output_csv/harvest_batches.csv' WITH (FORMAT csv, HEADER true, NULL '')
SELECT setval(pg_get_serial_sequence('harvest_batches','harvest_id'), COALESCE((SELECT MAX(harvest_id) FROM harvest_batches), 1), true);

\copy processing_runs FROM 'output_csv/processing_runs.csv' WITH (FORMAT csv, HEADER true, NULL '')
SELECT setval(pg_get_serial_sequence('processing_runs','run_id'), COALESCE((SELECT MAX(run_id) FROM processing_runs), 1), true);

\copy quality_grades FROM 'output_csv/quality_grades.csv' WITH (FORMAT csv, HEADER true, NULL '')
SELECT setval(pg_get_serial_sequence('quality_grades','grade_id'), COALESCE((SELECT MAX(grade_id) FROM quality_grades), 1), true);

\copy wholesale_shipments FROM 'output_csv/wholesale_shipments.csv' WITH (FORMAT csv, HEADER true, NULL '')
SELECT setval(pg_get_serial_sequence('wholesale_shipments','wholesale_id'), COALESCE((SELECT MAX(wholesale_id) FROM wholesale_shipments), 1), true);

\copy farmer_loans_reference FROM 'output_csv/farmer_loans_reference.csv' WITH (FORMAT csv, HEADER true, NULL '')
SELECT setval(pg_get_serial_sequence('farmer_loans_reference','reference_id'), COALESCE((SELECT MAX(reference_id) FROM farmer_loans_reference), 1), true);

\echo 'All CSVs loaded and sequences reset.'
